"""Configuration values for the Pet Connect weekly workflow."""

from __future__ import annotations

from pathlib import Path

# Listing sources to crawl. Each entry specifies the collection method:
# - "rss": use feed_url only (no Crawl4AI crawl)
# - "listing": crawl listing_url and rely on Gemini metadata extraction
SOURCE_SITES = [ 
    {
        "name": "Pet Gazette", 
        "method": "rss",
        "feed_url": "https://www.petgazette.biz/feed/",
        "max_articles": 20,
        "use_feed_content": True,
    },
    {
        "name": "Global Pet Industry", 
        "method": "rss",
        "feed_url": "https://globalpetindustry.com/feed/",
        "max_articles": 20,
        "use_feed_content": True,
    },
    {
        "name": "International Pet Food", 
        "method": "rss",
        "feed_url": "https://internationalpetfood.com/category/news/feed/", #
        "max_articles": 20,
        "use_feed_content": True,
    },
    {
        "name": "Petfood Industry",
        "method": "rss",
        "feed_url": "https://www.petfoodindustry.com/rss",
        "max_articles": 20,
        "use_feed_content": True,
    },
    {
        "name": "Pet Food Processing",
        "method": "rss",
        "feed_url": "https://www.petfoodprocessing.net/rss/topic/497-global-news",
        "max_articles": 20,
        "use_feed_content": False,
    },
    {
        "name": "Pet Business World",
        "method": "listing",
        "listing_url": "https://www.petbusinessworld.co.uk/trade-news", # (no date)
        "max_articles": 15,
    },
    {
        "name": "Pet Age",
        "method": "listing",
        "listing_url": "https://www.petage.com/category/topics/industry-news-catg/", #
        "max_articles": 15,
    },
    {
        "name": "Pets+ Magazine (Headlines)",
        "method": "rss",
        "feed_url": "https://petsplusmag.com/news/headlines/feed/",
        "max_articles": 20,
        "use_feed_content": True,
    },
    {
        "name": "Pets+ Magazine (Press Releases)",
        "method": "rss",
        "listing_url": "https://petsplusmag.com/news/press-releases/feed/", #
        "max_articles": 20,
        "use_feed_content": True,
    },
]

# Base substrings to exclude when Gemini extracts article URLs from listings.
NON_ARTICLE_SUBSTRINGS = [
    "/tag/",
    "/tags/",
    "/author/",
    "/authors/",
    "/about/",
    "/advertise/",
    "/media-kit/",
    "/contact/",
    "/events/",
    "/privacy",
    "/terms",
    "/newsletter",
    "/subscribe",
    "/products/",
    "/classifieds/",
    "/jobs/",
    "/shop/",
    "/sponsored/",
]

# Gemini evaluation threshold (inclusive) to consider an article relevant.
RELEVANCE_THRESHOLD = 4

# Maximum number of URLs to process per site when Gemini returns long lists.
DEFAULT_MAX_ARTICLES_PER_SITE = 15

# Async crawling behaviour.
CRAWLER_KWARGS = {}  # placeholder for future overrides (headers, etc.)
LISTING_THROTTLE_SECONDS = 0.4
ARTICLE_THROTTLE_SECONDS = 0.2

# Gemini request settings.
RELEVANCE_BATCH_SIZE = 24
SUMMARY_BATCH_SIZE = 5
SUMMARY_PAUSE_SECONDS = 4.0
ARTICLE_TEXT_MAX_CHARS = 6000

# Sponsor / exhibitor keywords to flag during full-text crawl.
SPONSOR_KEYWORDS = [
    "AskVet",
    "Butter Payments",
    "Embark Veterinary",
    "epiq Animal Health",
    "PWC",
    "Walmart",
    "Circa Healthcare",
    "FWD People",
    "Odie Pet Insurance",
    "Rover",
    "SoluPet Supplements",
    "Teletails",
    "Thompson Coburn",
    "Willoughby Design",
    "301 Inc",
    "Agrolimen",
    "Ancestry",
    "Independence Pet Group",
    "Synchrony",
    "Nestle Purina",
]

# Output artefacts generated by the workflow.
OUTPUT_PATHS = {
    "listing_articles": "pet_connect_articles_raw.json",
    "evaluated_articles": "pet_connect_articles_scored.json",
    "summaries": "pet_connect_articles_summarized.json",
}

# Email configuration overrides.
EMAIL_SETTINGS = {
    "template_name": "email_template.html",
    "template_dir": Path(__file__).resolve().parent,
    "subject_template": "Pet Connect Weekly News Summary - {today}",
    "from_name": "Pet Connect News Bot",
}
